/// <reference path="../../scripts/typings/angularjs/angular.d.ts" />
/// <reference path="../ts/global/global.ts" />
/// <reference path="../loancenter/loancenter.app.ts" />

// @todo - this is generated by the framework
//class Loan implements Loan {

//    active: srv.ILoanApplicationViewModel

//    constructor() {
//    }
//}
//factory.$inject = [];

//function factory() {
//    return new Loan();
//}

//angular.module('loanCenter').factory('Loan', factory);



