//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MeAndMyLoan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeAndMyLoan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MeAndMyLoan", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial deposit for your escrow account.
        /// </summary>
        internal static string HUDLine1001Title {
            get {
                return ResourceManager.GetString("HUDLine1001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homeowner&apos;s Insurance.
        /// </summary>
        internal static string HUDLine1002Title {
            get {
                return ResourceManager.GetString("HUDLine1002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortagage Insurance.
        /// </summary>
        internal static string HUDLine1003Title {
            get {
                return ResourceManager.GetString("HUDLine1003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Taxes.
        /// </summary>
        internal static string HUDLine1004Title {
            get {
                return ResourceManager.GetString("HUDLine1004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate Adjustment.
        /// </summary>
        internal static string HUDLine1007Title {
            get {
                return ResourceManager.GetString("HUDLine1007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title services and lender&apos;s title insurance.
        /// </summary>
        internal static string HUDLine1101Title {
            get {
                return ResourceManager.GetString("HUDLine1101Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement or closing fee.
        /// </summary>
        internal static string HUDLine1102Title {
            get {
                return ResourceManager.GetString("HUDLine1102Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s title Insurance.
        /// </summary>
        internal static string HUDLine1103Title {
            get {
                return ResourceManager.GetString("HUDLine1103Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lender&apos;s title Insurance.
        /// </summary>
        internal static string HUDLine1104Title {
            get {
                return ResourceManager.GetString("HUDLine1104Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lender&apos;s title policy limit.
        /// </summary>
        internal static string HUDLine1105Title {
            get {
                return ResourceManager.GetString("HUDLine1105Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s title policy limit.
        /// </summary>
        internal static string HUDLine1106Title {
            get {
                return ResourceManager.GetString("HUDLine1106Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent&apos;s portion of the total title Insurance premium to.
        /// </summary>
        internal static string HUDLine1107Title {
            get {
                return ResourceManager.GetString("HUDLine1107Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwriter&apos;s portion of the total title Insurance premium to.
        /// </summary>
        internal static string HUDLine1108Title {
            get {
                return ResourceManager.GetString("HUDLine1108Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Recording Charges.
        /// </summary>
        internal static string HUDLine1201Title {
            get {
                return ResourceManager.GetString("HUDLine1201Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Fees.
        /// </summary>
        internal static string HUDLine1202Title {
            get {
                return ResourceManager.GetString("HUDLine1202Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Taxes.
        /// </summary>
        internal static string HUDLine1203Title {
            get {
                return ResourceManager.GetString("HUDLine1203Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/County/Stamps.
        /// </summary>
        internal static string HUDLine1204Title {
            get {
                return ResourceManager.GetString("HUDLine1204Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State tax/Stamps.
        /// </summary>
        internal static string HUDLine1205Title {
            get {
                return ResourceManager.GetString("HUDLine1205Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required services that you can shop for.
        /// </summary>
        internal static string HUDLine1301Title {
            get {
                return ResourceManager.GetString("HUDLine1301Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commision paid at settlement.
        /// </summary>
        internal static string HUDLine703Title {
            get {
                return ResourceManager.GetString("HUDLine703Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Fee.
        /// </summary>
        internal static string HUDLine801aTitle {
            get {
                return ResourceManager.GetString("HUDLine801aTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Fees.
        /// </summary>
        internal static string HUDLine801bTitle {
            get {
                return ResourceManager.GetString("HUDLine801bTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Fees.
        /// </summary>
        internal static string HUDLine801cTitle {
            get {
                return ResourceManager.GetString("HUDLine801cTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker Fees.
        /// </summary>
        internal static string HUDLine801dTitle {
            get {
                return ResourceManager.GetString("HUDLine801dTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker Compensation Fees.
        /// </summary>
        internal static string HUDLine801eTitle {
            get {
                return ResourceManager.GetString("HUDLine801eTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwriting Fees.
        /// </summary>
        internal static string HUDLine801fTitle {
            get {
                return ResourceManager.GetString("HUDLine801fTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERS Fee.
        /// </summary>
        internal static string HUDLine801gTitle {
            get {
                return ResourceManager.GetString("HUDLine801gTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wire Fees.
        /// </summary>
        internal static string HUDLine801hTitle {
            get {
                return ResourceManager.GetString("HUDLine801hTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our origination charge.
        /// </summary>
        internal static string HUDLine801Title {
            get {
                return ResourceManager.GetString("HUDLine801Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credit or charge (points) for the specific interest rate chosen.
        /// </summary>
        internal static string HUDLine802Title {
            get {
                return ResourceManager.GetString("HUDLine802Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your adjusted origination charges.
        /// </summary>
        internal static string HUDLine803Title {
            get {
                return ResourceManager.GetString("HUDLine803Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal fee to.
        /// </summary>
        internal static string HUDLine804Title {
            get {
                return ResourceManager.GetString("HUDLine804Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit report to.
        /// </summary>
        internal static string HUDLine805Title {
            get {
                return ResourceManager.GetString("HUDLine805Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax service to.
        /// </summary>
        internal static string HUDLine806Title {
            get {
                return ResourceManager.GetString("HUDLine806Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood certification to.
        /// </summary>
        internal static string HUDLine807Title {
            get {
                return ResourceManager.GetString("HUDLine807Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Interest charges.
        /// </summary>
        internal static string HUDLine901Title {
            get {
                return ResourceManager.GetString("HUDLine901Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortage Insurance premium for.
        /// </summary>
        internal static string HUDLine902Title {
            get {
                return ResourceManager.GetString("HUDLine902Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homeowner&apos;s Insurance for.
        /// </summary>
        internal static string HUDLine903Title {
            get {
                return ResourceManager.GetString("HUDLine903Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA Funding Fee.
        /// </summary>
        internal static string HUDLine905Title {
            get {
                return ResourceManager.GetString("HUDLine905Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Insurance.
        /// </summary>
        internal static string HUDLine906Title {
            get {
                return ResourceManager.GetString("HUDLine906Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired..
        /// </summary>
        internal static string SessionExpiredMessage {
            get {
                return ResourceManager.GetString("SessionExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session is about to expire. Click OK button to continue with your applicaton..
        /// </summary>
        internal static string SessionWarningMessage {
            get {
                return ResourceManager.GetString("SessionWarningMessage", resourceCulture);
            }
        }
    }
}
